### PR TITLE
rotten tomatoes ratings

### PR DESCRIPTION
**Pull request by im85288**

### CODE REVIEW

**Comment by mgonzales71** [comment]
:tada: :grinning: :tada: 

Awesome! Thanks much appreciated to see this!  lol

:tomato: :tomato: :scream: :tomato: :tomato:

**Comment by im85288** [comment]
No problem, I love my rt ratings!

Marcel, just fixed a bug with collections

**Comment by marcelveldt** [comment]
Great stuff Ian! Can/will you also update the readme with the new properties please ?

**Comment by im85288** [comment]
Thanks marcel, yes just updated and now changed to use the OMDB for info rather than direct to rotten tomatoes as it does not need an API key and also provides the rotten tomatoes critic review

**Comment by marcelveldt** [comment]
Do you mind editing the conflicts? I just checked in my changes to the caching and looks like it conflicts somewhere.

**Comment by im85288** [comment]
Yeah sure, I'm not in at the moment so will check in about an hour

**Comment by im85288** [comment]
ok I'll close this one as it's becoming a pain to mere

**Pull request closed without merging**
