### PR TITLE
added by genre widgets

### PR DESCRIPTION
**Pull request by im85288**

### CODE REVIEW

**Comment by marcelveldt** [comment]
Looking fine, great addition to the script, thanks.

One little comment: please also add your widget cache property to the KodiMonitor.py, otherwise the cache will never be refreshed and it keeps loading the same content untill restart.

method refreshvideowidgets in kodimonitor.py....

**Comment by im85288** [comment]
Thanks will do in a couple of hours.

Do you think it will be possible to do a "by actor" widget? Possibly by caching the cast members into a table with associated movies..had a look but it does not seem obvious

**Comment by marcelveldt** [comment]
OK, can you add that in and squash the commits, thanks in advance!
I will publish the skinhelper to the emby beta repo tonight so if you hurry it will already be included ;-)

"by actor" widget is possible but will not be very fast. Only way to do this properly is to loop through the movies to find an actor.. or... maybe the json api will allow filtering on actor name. Maybe a simple "cast contains x" query will suffice ?

**Comment by im85288** [comment]
Thanks, I added the info to KodiMonitor now. 

What I was thinking for the "by actor" was to make a map of actor name to movie whenever the getcast method was called...so it ends up with a big map such as:

Emily Stone - Harry Potter
Emily Stone - Harry Potter and Prisoners 

etc etc

Having looked at the JSON Api I cannot see anything that would help...maybe a simpler one would be "by director" as at least you can filter movies by the director.

Another one I had in mind which could be useful for TV Shows is by studio. In plex for example you have recommendations such as "TV Shows by Fox Studios" 

Lastly I was thinking of adding a "Top rated unwatched movies" one but that is achievable via a skin playlist so maybe quicker to do it there :)

**Comment by marcelveldt** [comment]
Thanks Ian for the PR, will merge it.

Hmmm, it's an option with the cast details but not a very fancy one because when you're not using the getcast method that map won't exist.
I'll have some spare time within a couple of days, Ill see where I can get with this.
First get the initial version to the Kodi repo.

**Pull request merged**
