### PR TITLE
add material design color palette

### PR DESCRIPTION
**Pull request by mgonzales71**
if you would like to add it I made a color palette based on google's material design.
source: http://www.google.com/design/spec/style/color.html#

### CODE REVIEW

**Comment by marcelveldt** [comment]
Hey Mario,

any chance you could put the colors in the correct order ?
Also in scrip-skin-helper-ColorPicker.xml it is possible to have an alternate itemlayout to match the palette.

Looks like you need to have 9 rows

**Comment by mgonzales71** [comment]
I was wondering how you did that with the other palettes.

I will have to look at that and fix it up for you.

Mario

----- Original Message -----

**Comment by marcelveldt** [comment]
Well, I didn't but braz created them. The only way is the painfull process of putting the color tags in the right order and adjust the itemlayout to match it.

So you need to define how many rows and columns you need and adjust your itemlayour to that.
The width/heighth of the itemlayout depends on the number of items in your palette.

Take a look at the 2 palettes that are already in there, they are both sorted in the correct order and

**Comment by mgonzales71** [comment]
ok updated colors.xml with sorted entries.

using this test conditional and a cell size of 40x125 (height x width) I get what you see in screenshot below:

```
        <itemlayout height="40" width="125" condition="StringCompare(Window.Property(palettename),material-design)">
            <control type="image">
                <width>92%</width>
                <height>92%</height>
                <texture border="5">$INFO[ListItem.Icon]</texture>
            </control>
        </itemlayout>
        <focusedlayout height="40" width="125" condition="StringCompare(Window.Property(palettename),material-design)">
            <control type="group">
                <animation effect="zoom" time="200" tween="sine" easing="inout" start="100" end="164" center="auto">Focus</animation>
                <control type="image">
                    <width>92%</width>
                    <height>92%</height>
                    <texture border="5">$INFO[ListItem.Icon]</texture>
                </control>
            </control>
        </focusedlayout>
```

The palette looks good!  but the only problem is I can't get my code changes to both the script and skin to play nice with all the other palettes - I kept getting unexpected results.... so maybe you can help do that part?  :pray:  :grinning:  thanks Marcel - eager to see how you do it so I can learn what I did wrong.

**Comment by mgonzales71** [comment]
FYI - here is the code for script-skin_helper_service-ColorPicker.xml I was trying to use that didn't seem to work..

http://pastebin.com/qC7guDGK

**Comment by marcelveldt** [comment]
Replace this:

"!StringCompare(Window.Property(palettename),basic) | !StringCompare(Window.Property(palettename),material-design)

with this:

"!StringCompare(Window.Property(palettename),basic) + !StringCompare(Window.Property(palettename),material-design)

**Comment by mgonzales71** [comment]
check out this link... may be worth looking into - http://stackoverflow.com/questions/8915113/sort-hex-colors-to-match-rainbow

**Comment by mgonzales71** [comment]
ok - should be all ready to go now... man I can't believe I missed that OR not being an AND - thanks for the catch.  after 40 mins and being so late I gave up. 
thanks again! :)

**Comment by marcelveldt** [comment]
Thanks Mario, I will merge it and test it. Great work.

As for the sort by code: already tried that and actually removed it. Way better to just sort with the xml file because that will give the skinner maximum control over how they want to display all colors.

**Comment by mgonzales71** [comment]
The other day when I came across this site:  https://www.materialpalette.com/

Had the thought that it could be a way to give an easy "auto" quick pick color theme for the skin.

you basically pick any 2 colors from the base material design colors and it presents a generated palette

you could map the generated palette to various skin elements.

so for example if you pick green and blue-grey

link would be https://www.materialpalette.com/green/blue-grey to view it 

the downloadable xml would be at https://www.materialpalette.com/download.xml/green/blue-grey

just replace the colors of choice in the link and you get an XML palette of 8 complimentary colors

anyway - was a thought I had and wanted to share.   i personally think that it would be cool :)

**Comment by mgonzales71** [comment]
and if you didn't want to rely on the site could download all the variations into a static file.

**Pull request merged**
